name: othala
description: Othala wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Utility plugins
  http: ^0.13.4
  date_format: ^2.0.6

  # Bitcoin plugins
  xchain_dart:
    git:
      url: https://github.com/renejeronimus/xchain_dart
      ref: main

  # File/storage plugins
  flutter_secure_storage: ^5.0.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.11

  # UI/Component plugins
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  page_view_indicators: ^2.0.0
  flutter_emoji:
    git: https://github.com/cek-cek/flutter-emoji
  # pubdev qr_flutter 4.0.0 contains outdated package:qr/qr.dart with error.
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  # Flutter Launcher Icons is a command-line tool which simplifies the task
  # of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
